import React, { useState, useEffect } from 'react';
import { FileText, Download, Printer, Calendar, ShieldCheck, Zap, DollarSign } from 'lucide-react';
import { api } from '../api/client';

export const ReportsPage: React.FC = () => {
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [selectedMonth, setSelectedMonth] = useState(9);

  const fetchReport = async (m: number) => {
    setLoading(true);
    try {
      const data = await api.getMonthlyReport(2026, m);
      setReport(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReport(selectedMonth);
  }, [selectedMonth]);

  const handleDownloadCsv = () => {
    window.open(`/api/reports/export-csv?year=2026&month=${selectedMonth}`, '_blank');
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading || !report) {
    return <div className="text-center py-20 text-slate-400 text-sm">Compiling monthly energy audit report...</div>;
  }

  const s = report.summary;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-2 border-b border-slate-800">
        <div>
          <h2 className="text-xl font-bold text-white tracking-tight flex items-center space-x-2">
            <FileText className="w-5 h-5 text-indigo-400" />
            <span>Energy Audit & Monthly Reporting Center</span>
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Formal commercial-grade electricity consumption audit, appliance breakdown, and cost reconciliation.
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <select
            value={selectedMonth}
            onChange={(e) => setSelectedMonth(Number(e.target.value))}
            className="bg-slate-900 border border-slate-800 text-white text-xs rounded-xl px-3 py-1.5 focus:outline-none focus:border-emerald-500"
          >
            <option value={8}>August 2026</option>
            <option value={9}>September 2026 (Current)</option>
          </select>

          <button
            onClick={handleDownloadCsv}
            className="flex items-center space-x-1.5 px-3 py-1.5 bg-slate-900 hover:bg-slate-800 text-slate-200 border border-slate-800 rounded-xl text-xs font-semibold"
          >
            <Download className="w-3.5 h-3.5 text-emerald-400" />
            <span>Export CSV</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center space-x-1.5 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-semibold"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Audit Report</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document Card */}
      <div className="p-8 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-8 print:bg-white print:text-black print:p-0 print:border-none">
        {/* Document Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-800 pb-6 gap-4">
          <div>
            <span className="text-xs font-bold text-emerald-400 tracking-wider uppercase">
              Official Monthly Audit Report
            </span>
            <h3 className="text-2xl font-black text-white mt-1">{report.title}</h3>
            <p className="text-xs text-slate-400 mt-1">Audit Period: {report.period} • Tariff Rate: ₹{report.tariff_rate}/kWh</p>
          </div>
          <div className="text-right">
            <span className="text-xs text-slate-400">Generated by</span>
            <p className="text-sm font-bold text-white">VimalEnergy AI Smart Platform</p>
            <span className="inline-block mt-1 px-2 py-0.5 rounded text-[10px] font-bold bg-cyan-500/10 text-cyan-400 border border-cyan-500/30">
              SIMULATION CERTIFIED
            </span>
          </div>
        </div>

        {/* Executive Summary Metrics */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase font-semibold">Total Energy</span>
            <p className="text-xl font-extrabold text-white mt-1">{s.total_energy_kwh} kWh</p>
            <p className="text-[11px] text-slate-500 mt-0.5">Daily Avg: {s.avg_daily_kwh} kWh/day</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase font-semibold">Estimated Billing</span>
            <p className="text-xl font-extrabold text-amber-400 mt-1">₹{s.total_cost.toFixed(2)}</p>
            <p className="text-[11px] text-slate-500 mt-0.5">Slab rates applied</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase font-semibold">Verified Energy Saved</span>
            <p className="text-xl font-extrabold text-emerald-400 mt-1">{s.energy_saved_kwh} kWh</p>
            <p className="text-[11px] text-slate-500 mt-0.5">Through smart relays</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase font-semibold">Peak Demand</span>
            <p className="text-xl font-extrabold text-rose-400 mt-1">{(s.peak_power_w / 1000).toFixed(2)} kW</p>
            <p className="text-[11px] text-slate-500 mt-0.5">Grid emission: {s.co2_emissions_kg} kg CO2</p>
          </div>
        </div>

        {/* Appliance Breakdown Ledger */}
        <div className="space-y-3">
          <h4 className="text-sm font-bold text-white uppercase tracking-wider">Appliance Consumption & Cost Breakdown</h4>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-slate-800 text-slate-400">
                  <th className="pb-2 font-semibold">Appliance</th>
                  <th className="pb-2 font-semibold">Location</th>
                  <th className="pb-2 font-semibold">Category</th>
                  <th className="pb-2 font-semibold text-right">Operating Hours</th>
                  <th className="pb-2 font-semibold text-right">Consumption (kWh)</th>
                  <th className="pb-2 font-semibold text-right">Estimated Cost (₹)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60">
                {report.appliances.map((app: any, idx: number) => (
                  <tr key={idx} className="hover:bg-slate-800/20">
                    <td className="py-2.5 font-bold text-white">{app.name}</td>
                    <td className="py-2.5 text-slate-400">{app.room_name}</td>
                    <td className="py-2.5 text-slate-400">{app.category}</td>
                    <td className="py-2.5 text-right text-slate-300 font-mono">{app.operating_hours} hrs</td>
                    <td className="py-2.5 text-right font-bold text-emerald-400">{app.total_energy_kwh.toFixed(1)}</td>
                    <td className="py-2.5 text-right font-bold text-amber-400">₹{app.total_cost.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Key Recommendations */}
        <div className="space-y-3 pt-4 border-t border-slate-800">
          <h4 className="text-sm font-bold text-white uppercase tracking-wider">Audit Recommendations & Actions</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {report.recommendations.map((r: any) => (
              <div key={r.id} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-xs">
                <span className="font-bold text-white block">{r.title}</span>
                <p className="text-slate-400 mt-1">{r.description}</p>
                <div className="mt-2 text-[11px] text-emerald-400 font-semibold">
                  Target Saving: {r.potential_saving_kwh} kWh (₹{r.potential_saving_cost})
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
